### ISSUE TITLE
哥们，单独的RottenPotato提权有吗？弄了好久都单独的dll都没有成功

### ISSUE THREAD

**Issue by wpf97** [evi1ox/MSSQL_BackDoor#2]

**Comment by evi1ox** [comment]
https://github.com/foxglovesec/RottenPotato 这个项目里面有打包好的

**Comment by wpf97** [comment]
这是打包的exe，我是想弄成这样的
![0DD412A2-07F7-4547-939E-D1250034994E](https://user-images.githubusercontent.com/22408189/113386204-4e328300-93bc-11eb-99f1-b9c0779c8ebb.jpeg)

**Comment by evi1ox** [comment]
那你需要单独编写c# StoredProcedures

参考如下:
https://github.com/evi1ox/MSSQL_BackDoor/blob/master/MSSQL-Fileless-Rootkit-WarSQLKit/WarSQLKit/StoredProcedures.cs#L66

**Comment by wpf97** [comment]
对，我就是没弄好。您看您有时间吗？能帮忙编写一个吗？感谢🙏

**Comment by evi1ox** [comment]
不好意思, 请自行研究下, 而且这个项目过段时间准备重构, 即使原作者的思路非常棒
